### ISSUE TITLE
Consolidate all the `/url` endpoints behind a consolidated `/api` endpoint

### ISSUE THREAD

**Issue by ezzizzle** [ezzizzle/ziz-shortener#11]
Currently the endpoints for adding, deleting and getting details for a shortened URL all sit under the root `/url` endpoint. It would be better to serve this under `/api/url` to make it easier to secure the API.

Consider whether to move the `/api-docs` endpoint as well.

**Comment by Troy96** [comment]
Hi,

Can I work on this?

**Comment by ezzizzle** [comment]
For sure, go for it. Let me know if the description isn't clear (I had written it for myself).

**Comment by Troy96** [comment]
Yeah cool. I have cloned it installed the dependencies and have run it. Will do the issue now. Did you use any boilerplate for the project?

**Comment by ezzizzle** [comment]
Thanks for working on this @Troy96. I've merged in your changes.

**Comment by Troy96** [comment]
Thanks Eric for providing this opportunity. Learned a lot from the project.
:)
